fix: kaspersky filter pattern overmatching sdata (#2058)
splunk/splunk-connect-for-syslog pull request #2126
Opened 2023-08-02 08:55 UTC by ikheifets-splunk

2023-08-02 09:01 UTC, ikheifets-splunk commented on tests/test_vmware.py
> +def test_vmware_overlapping_with_another_sdata(
Originally in issue `kasperksy` filter overmatch value of `VMware`

2023-08-02 09:15 UTC, ikheifets-splunk commented on package/etc/conf.d/conflib/syslog/app-syslog-kaspersky_syslog.conf
> +        match('[[^\@]@23668' value('SDATA'))
also might use `[event@23668`, but it's seems that would be more generic

2023-08-02 11:31 UTC, rjha-splunk commented on package/etc/conf.d/conflib/syslog/app-syslog-kaspersky_syslog.conf
> +        match('event@23668' value('SDATA'))
filter {                                                        
        match('@23668' value('.SDATA.*'))                   
    };

The filter should be updated as there is still a chance in main data there is event@23668888 etc.

2023-08-02 11:32 UTC, rjha-splunk requested changes
https://github.com/splunk/splunk-connect-for-syslog/pull/2126/files#r1281776830 should be updated

2023-08-03 08:53 UTC, rjha-splunk approved these changes

2023-08-03 08:53 UTC, merged

2023-08-03 09:08 UTC, srv-rr-github-token commented
:tada: This PR is included in version 3.1.3 :tada:

The release is available on [GitHub release](https://github.com/splunk/splunk-connect-for-syslog/releases/tag/v3.1.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: