feat: create new filter for a10networks
splunk/splunk-connect-for-syslog pull request #2143
Opened 2023-08-17 08:55 UTC by ikheifets-splunk

2023-08-17 09:35 UTC, mstopa-splunk requested changes

2023-08-17 09:35 UTC, mstopa-splunk commented on docs/sources/vendor/a10networks/vthunder.md
> +| -| a10networks:vThunder| netwaf         | none           |
key should be `vendor_product`, like: https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/Citrix/netscaler/

2023-08-17 09:35 UTC, mstopa-splunk commented on docs/sources/vendor/a10networks/vthunder.md
> +| Splunk Add-on  | None                                                                                                    |
Not sure if community-owned add-ons count but there are some addons made by A10 networks that can be checked against regarding the sourcetype: https://splunkbase.splunk.com/apps?keyword=thunder

2023-08-17 13:27 UTC, mstopa-splunk commented on docs/sources/vendor/a10networks/vthunder.md
> +|a10_vthunder| a10networks:vThunder| netwaf         | none           |
I failed to redirect event to another index with `splunk_metadata.csv` using this key:
```
a10_vthunder,index,main
```

Worked when changed to:
```
a10networks_vThunder,index,main
```

2023-08-17 13:32 UTC, mstopa-splunk approved these changes

2023-08-18 06:28 UTC, mateuszpierzchala-splunk approved these changes

2023-08-21 08:41 UTC, merged

2023-08-21 08:55 UTC, srv-rr-github-token commented
:tada: This PR is included in version 3.3.0 :tada:

The release is available on [GitHub release](https://github.com/splunk/splunk-connect-for-syslog/releases/tag/v3.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: