Docs/update doc sections
splunk/splunk-connect-for-syslog pull request #2175
Opened 2023-09-21 08:20 UTC by mstopa-splunk

2023-10-12 03:27 UTC, jenworthington requested changes

2023-10-12 03:27 UTC, jenworthington commented on docs/lite.md
>  The Splunk platform is the destination for the syslog data. Splunk allows for comprehensive analysis, searching, and visualization of the processed data.
SC4S sends your syslog data to the Splunk platform where you can perform comprehensive analysis, searching, and visualization of the processed data.

2023-10-12 03:27 UTC, jenworthington commented on docs/lite.md
>  SC4S Lite receives the syslog data and routes it through the appropriate parsers, as defined by user configurations.
SC4S Lite receives the syslog data and routes it through the parsers defined by your configurations. These parsers in the plugin module process the data, includig parsing, filtering, and enriching the data with metadata.

SC4S Lite forwards the processed syslog data to the Splunk platform over the HTTP Event Collector (HEC).

2023-10-12 03:27 UTC, jenworthington commented on docs/lite.md
> +Source systems send syslog data to SC4S Lite. The data may be transmitted via UDP or TCP depending on the system's capabilities and configurations.
Source systems send syslog data to SC4S Lite through UDP or TCP, depending on your system's capabilities and configurations.

2023-10-12 03:27 UTC, jenworthington commented on docs/lite.md
>  ## Scalability and Performance
SC4S Lite provides superior performance and scalability by implementing lightweight architecture and pluggable parsers that distribute the processing load. It is also packaged with an eBPF program to help further enhance performance.

2024-01-16 10:08 UTC, rjha-splunk approved these changes

2024-01-16 10:08 UTC, ikheifets-splunk approved these changes

2024-01-16 10:11 UTC, merged

2024-01-17 13:51 UTC, srv-rr-github-token commented
:tada: This PR is included in version 3.16.0 :tada:

The release is available on [GitHub release](https://github.com/splunk/splunk-connect-for-syslog/releases/tag/v3.16.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: