Support infoblox
splunk/splunk-connect-for-syslog pull request #738
Opened 2020-09-28 13:59 UTC by mchavda-splunk

Jira: ADDON-29621, ADDON-28603, ADDON-28680

* Add support for the Infoblox events

2020-09-28 14:14 UTC, rfaircloth-splunk requested changes

2020-09-28 14:14 UTC, rfaircloth-splunk commented on docs/sources/InfoBlox/index.md
> -| nix_syslog    | nix:syslog      | osnix          | none          |
infoblox like many appliances is running linux as the base OS we don't want to propigate the linux kos across all add-ons so the nix_syslog should stay

2020-09-28 14:14 UTC, rfaircloth-splunk commented on package/etc/conf.d/log_paths/lp-infoblox.conf.tmpl
> +            r_set_splunk_dest_default(sourcetype("infoblox:port"),  source("program:${.PROGRAM}"))
this is incorrect

2020-09-28 14:14 UTC, rfaircloth-splunk commented on package/etc/conf.d/log_paths/lp-infoblox.conf.tmpl
> +            r_set_splunk_dest_default(sourcetype("infoblox:threatprotect"),  source("program:${.PROGRAM}"))
this is a breaking change

2020-09-30 18:31 UTC, themrkeys approved these changes

2020-09-30 18:32 UTC, rfaircloth-splunk approved these changes

2020-09-30 18:32 UTC, merged