Feature/addon 32234 create sc4s filter mcafee nsp
splunk/splunk-connect-for-syslog pull request #896
Opened 2021-01-18 16:23 UTC by yashs-crest

Added sc4s filter for McAfee NSP and added/modified its related files

2021-01-19 09:05 UTC, yashs-crest commented
I have read the CLA Document and I hereby sign the CLA

2021-01-19 09:05 UTC, yashs-crest commented
recheck

2021-01-19 16:35 UTC, rfaircloth-splunk requested changes

2021-01-19 16:35 UTC, rfaircloth-splunk commented on package/etc/conf.d/log_paths/lp-mcafee_nsp.conf.tmpl
> +  match("mcafee_nsp", value("fields.sc4s_vendor_product") type(glob));
because this message is valid BSD, and there are 3 unique values of PROGRAM we should use that as the filter so this can work with zero config oob.

2021-01-20 22:30 UTC, rfaircloth-splunk approved these changes

2021-01-20 22:31 UTC, merged

2021-01-20 22:38 UTC, rfaircloth-splunk commented
:tada: This PR is included in version 1.46.0-develop.1 :tada:

The release is available on [GitHub release](https://github.com/splunk/splunk-connect-for-syslog/releases/tag/v1.46.0-develop.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-01-21 13:55 UTC, rfaircloth-splunk commented
:tada: This PR is included in version 1.46.0 :tada:

The release is available on [GitHub release](https://github.com/splunk/splunk-connect-for-syslog/releases/tag/v1.46.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: